schema_version: 1

project:
  name: 2026-009-01.cad.HUB75-display-frame

profiles:
  - type: scad
    config: project.scad.yml

dependencies:
  - name: tool.scad-project
    role: tooling
    type: git-submodule
    url: https://github.com/brainboxemb/tool.scad-project.git
    path: tools/tool.scad-project
    ref: v0.11.0

  - name: lib.scad.hub75
    role: external
    type: git-submodule
    url: https://github.com/brainboxemb/lib.scad.hub75.git
    path: dsg/openscad/ext/lib.scad.hub75
    ref: v0.1.2
