name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*"
    paths:
      - "dsg/**"
      - "project.yml"
      - ".gitmodules"
      - "tools/tool.scad-project"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "dsg/**"
      - "project.yml"
      - ".gitmodules"
      - "tools/tool.scad-project"
      - ".github/workflows/build.yml"

permissions:
  contents: write
  packages: read

jobs:
  build:
    # Keep only the newest run for this workflow and Git ref.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: brainboxemb/tool.scad-project/.github/workflows/project-build.yml@v0.8.0
    with:
      artifact_name: hub75-display-frame-build
