name: PR cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-pr-cleanup.yml@8e0bd8f3b31e421586554f2bc7cbd914d05836b6
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_branch_prefix: dev/pr
      delete_source_branch: true
